site_title = "MyArxiv"
limit_days = 7
cache_url = "https://dkkyjy.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "astro-ph.HE"
title = "High Energy Astrophysical Phenomena"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
